//@baseUrl = http://localhost:3000/api/v1
@baseUrl = http://192.168.31.6:3000/api/v1

@authorization = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMDIxYzljZTk4NzE1NTVkOGU0ODczYyIsImlhdCI6MTY0NDMwNTk3MywiZXhwIjoxNjQ0OTEwNzczfQ.Bsy9OoopywHRTHNFVI_I8gO7laLgFTzQzglfIMzqjqI

# 登录

### 用户登录(管理员、顾客)
POST {{baseUrl}}/login
Content-Type: application/json

{
  "user_name": "user1",
  "password": "12345678"
}


# 管理员

### 管理员注册
POST {{baseUrl}}/register/admin
Content-Type: application/json

{
  "user_name": "user2",
  "password": "123456"
}


# 顾客

### 顾客注册
POST {{baseUrl}}/register/customer
Content-Type: application/json

{
  "user_name": "user",
  "password": "12345678",
  "name":"用户1",
  "phone":"18569853214",
  "address":"云南昆明"
}


### 顾客更新
PUT {{baseUrl}}/customers/620256eee9871555d8e48750
{{authorization}}
Content-Type: application/json

{
  "name": "更新顾客1",
  "phone": "18514964682",
  "address": "张杨路3611号金桥国际商业广场1座B1层"
}


### 获取顾客列表
GET {{baseUrl}}/customers?offset=0&limit=1
{{authorization}}


### 获取顾客信息
GET {{baseUrl}}/customers/620256eee9871555d8e48750
{{authorization}}


//  ToDo: 删除顾客时并不能删除user表里面的下的信息。只能删除顾客表里面的信息
### 删除顾客
DELETE {{baseUrl}}/customers/6205162117c59246bce31247
{{authorization}}


# 商家

# 商品

# 销售单

# 进货单