//@baseUrl = http://localhost:3000/api/v1
@baseUrl = http://172.26.86.113:3000/api/v1

@authorization = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMGE1Zjk0NjVkYThmM2ViY2UyMmFmYSIsImlhdCI6MTY0OTMwNTc0OSwiZXhwIjoxNjQ5OTEwNTQ5fQ.uGnI-xBbg4digL4R-Bj_Y6CqQ1a0mqHJnUIC6AJc--A
# 登录

### 用户登录(管理员、顾客)
POST {{baseUrl}}/login
Content-Type: application/json

{
  "user_name": "user9",
  "password": "123456789"
}



# 管理员

### 管理员注册
POST {{baseUrl}}/register/admin
Content-Type: application/json

{
  "user_name": "user2",
  "password": "123456"
}



# 顾客

### 顾客注册
POST {{baseUrl}}/register/customer
Content-Type: application/json

{
  "user_name": "user",
  "password": "12345678",
  "name":"用户1",
  "phone":"18569853214",
  "address":"云南昆明"
}


### 更新顾客信息
PUT {{baseUrl}}/customers/620256eee9871555d8e48750
{{authorization}}
Content-Type: application/json

{
  "name": "更新顾客1",
  "phone": "18514964682",
  "address": "张杨路3611号金桥国际商业广场1座B1层"
}


### 获取顾客列表
GET {{baseUrl}}/customers?offset=0&limit=1
{{authorization}}


### 获取顾客信息
GET {{baseUrl}}/customers/620256eee9871555d8e48750
{{authorization}}


//  ToDo: 删除顾客时并不能删除user表里面的下的信息。只能删除顾客表里面的信息  
//已解决，只不过不知道要哪个版本，老版本不删除user 新版本删除user
### 删除顾客
DELETE {{baseUrl}}/customers/62025ff2e9871555d8e48760
{{authorization}}


# 商家

// ToDo: 顾客user_name和商家user_name会出现不能相同，因为不论顾客还是商家都属于user
### 商家注册
POST {{baseUrl}}/register/merchant
Content-Type: application/json

{
   "user_name": "user9",
   "password": "123456789",
   "name":"民心商店",
   "phone":"15965832145",
   "introduction":"农资经营",
   "address":"云南省大坡麻拉"
}


### 更新商家
PUT  {{baseUrl}}/merchants/620a5f9565da8f3ebce22afc
{{authorization}}
Content-Type: application/json

{
  "name": "盒马",
  "phone": "18514965824",
  "introduction": "盒马是阿里巴巴集团旗下，以数据和技术驱动的新零售平台。盒马希望为消费者打造社区化的一站式新零售体验中心，用科技和人情味带给人们“鲜美生活”",
  "address": "张杨路3611号金桥国际商业广场1座B1层",
  "delivery_cost": 5,
  "min_delivery_price": 20
}


### 获取商家列表
GET {{baseUrl}}/merchants?offset=0&limit=1
{{authorization}}


### 获取商家信息
GET {{baseUrl}}/merchants/6207b16c95fdf50bb04133f7
{{authorization}}


### 删除商家
DELETE {{baseUrl}}/merchants/6207b16c95fdf50bb04133f7
{{authorization}}



# 商品

### 新增商品
POST {{baseUrl}}/merchandises
{{authorization}}
Content-Type: application/json

{
  "name": "敌杀死",
  "price": 20,
  "qrcode":1524224
}


### 更新商品信息
PUT {{baseUrl}}/merchandises/620fac3c7a5dc3356c7ab883
{{authorization}}
Content-Type: application/json

{
  "name":"敌敌畏",
  "price":"25",
  "specs":"袋",
  "productionDate":"",
  "shelfLife":"",
  "manufacturer":"",
  "qrcode":""
}


### 获取商品列表
GET {{baseUrl}}/merchandises
{{authorization}}


### 获取商品信息
GET {{baseUrl}}/merchandises/620fac3c7a5dc3356c7ab883
{{authorization}}


### 删除商品
DELETE {{baseUrl}}/merchandises/620fac3c7a5dc3356c7ab883
{{authorization}}


# # 销售单

### 新增销售单
POST {{baseUrl}}/saleOrders
{{authorization}}


### 更新销售单
PUT {{baseUrl}}/saleOrders/6213750ec70472232c9fd005
{{authorization}}
Content-Type: application/json

{
  "amounts":23,
  "prices":120
}


### 获取销售单列表
GET {{baseUrl}}/saleOrders
{{authorization}}


### 获取销售单信息
GET {{baseUrl}}/saleOrders/6213750ec70472232c9fd005
{{authorization}}


### 删除销售单
DELETE {{baseUrl}}/saleOrders/6213750ec70472232c9fd005
{{authorization}}


# 进货单

### 新增进货单
POST {{baseUrl}}/purchaseOrders
{{authorization}}


### 更新进货单
PUT {{baseUrl}}/purchaseOrders/624e70d114c5ab17f8a2adf4
{{authorization}}
Content-Type: application/json

{
  "totalamounts":23,
  "totalprices":120
}


### 获取进货单列表
GET {{baseUrl}}/purchaseOrders
{{authorization}}


### 获取进货单信息
GET {{baseUrl}}/purchaseOrders/624e68f17c5f5635ac2c12b8
{{authorization}}


### 删除销售单
DELETE {{baseUrl}}/purchaseOrders/624e68f17c5f5635ac2c12b8
{{authorization}}


# 批发商


### 新增批发商
POST {{baseUrl}}/wholesalers
{{authorization}}
Content-Type: application/json

{
  "name": "人民商店"
}


### 更新批发商
PUT {{baseUrl}}/wholesalers/6214db82fddf321fec5a239f
{{authorization}}
Content-Type: application/json

{
  "phone":"15869324569",
  "address":"将军镇521号"
}


### 获取批发商列表
GET {{baseUrl}}/wholesalers
{{authorization}}


### 获取商家信息
GET {{baseUrl}}/wholesalers/6214db82fddf321fec5a239f
{{authorization}}


### 删除批发商
DELETE {{baseUrl}}/wholesalers/6214db82fddf321fec5a239f
{{authorization}}



# 进货单Item

### 新增进货单Item
POST {{baseUrl}}/purchaseOrdersItem
{{authorization}}

### 更新进货单Item
PUT {{baseUrl}}/purchaseOrdersItem/624e795510e5dc391036d7a4
{{authorization}}
Content-Type: application/json

{
  "amounts":23,
  "price":10,
  "totalprices":120
}


### 删除销售单
DELETE {{baseUrl}}/purchaseOrdersItem/624e795510e5dc391036d7a4
{{authorization}}
