@baseUrl = http://172.26.86.113:3000/api/v1

@baseUrl = http://43.138.144.204:3000/api/v1
@authorization = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNjg4MjlhZTRhYjhlNmU3NDg0ZDI1OSIsImlhdCI6MTY1MTAyMTA3MywiZXhwIjoxNjUxNjI1ODczfQ.tbHULwW3JXxLGAycdV-F2aq-ZRHlZiPG8zSK2wvC_lY


 # 销售单

### 新增销售单
POST {{baseUrl}}/saleOrders
{{authorization}}


### 更新销售单
PUT {{baseUrl}}/saleOrders/6267539cd656ca6a90292c5d
{{authorization}}
Content-Type: application/json

{
    "customer":"6263cd40526ac6545c427267"
}


### 获取销售单列表
GET {{baseUrl}}/saleOrders
{{authorization}}
 

### 获取销售单信息
GET {{baseUrl}}/saleOrders/6267539cd656ca6a90292c5d
{{authorization}}


### 删除销售单
DELETE {{baseUrl}}/saleOrders/6267539cd656ca6a90292c5d
{{authorization}}


# 销售单Item

### 新增销售单Item
POST {{baseUrl}}/saleOrdersItem
{{authorization}}
Content-Type: application/json

{
  "saleOrder":"6266900c8f92d6153c798479",
  "merchandises":"626689008f47d34dd01cdbbe"
}

### 更新销售单Item
PUT {{baseUrl}}/saleOrdersItem/6267583923be8658a4cf2a8a
{{authorization}}
Content-Type: application/json

{
  "amounts":4,
  "price":50,
  "merchandises":"626688de8f47d34dd01cdbba"
}

### 获取销售单详情
GET {{baseUrl}}/saleOrdersItem/saleOrder/6266900c8f92d6153c798479
{{authorization}}

### 删除进货单Item
DELETE {{baseUrl}}/saleOrdersItem/6267583923be8658a4cf2a8a
{{authorization}}
