//@baseUrl = http://localhost:3000/api/v1

//@baseUrl = http://192.168.16.178:3000/api/v1
@baseUrl = http://172.26.86.113:3000/api/v1

@authorization = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNzEwYzVmNjEwYzYyNGY1YzRiZjgzNCIsImlhdCI6MTY1MTY2NzcyOCwiZXhwIjoxNjUyMjcyNTI4fQ.V8A4Jur8xhP2BrgneX08TGeKNsS0xLMWMNxHl9fj0xg

# 进货单

### 新增进货单
POST {{baseUrl}}/purchaseOrders
{{authorization}}
Content-Type: application/json

{
  "date":"2022-03-05"
}


### 更新进货单
PUT {{baseUrl}}/purchaseOrders/62689cda880b9559e4ad0ddc   
{{authorization}}
Content-Type: application/json

{
 "wholesaler":"6268d5524b955c3138063c42"
}


### 获取进货单列表
GET {{baseUrl}}/purchaseOrders
{{authorization}}


### 获取进货单信息
GET {{baseUrl}}/purchaseOrders/62689cda880b9559e4ad0ddc
{{authorization}}


### 删除进货单
DELETE {{baseUrl}}/purchaseOrders/624e68f17c5f5635ac2c12b8
{{authorization}}



# 进货单Item

### 新增进货单Item
POST {{baseUrl}}/purchaseOrdersItem
{{authorization}}
Content-Type: application/json

{
  "purchaseOrder":"62689cda880b9559e4ad0ddc",
  "merchandises":"626939deb431084f24c74f34"
}

### 更新进货单Item
PUT {{baseUrl}}/purchaseOrdersItem/62693b82295cb52b9456b839
{{authorization}}
Content-Type: application/json

{
  "amounts":4,
  "merchandises":"626688de8f47d34dd01cdbba"
}

### 获取进货单详情
GET {{baseUrl}}/purchaseOrdersItem/purchaseOrder/62689cda880b9559e4ad0ddc
{{authorization}}


### 删除进货单Item
DELETE {{baseUrl}}/purchaseOrdersItem/62662c6fb796f93e70c619c1
{{authorization}}
