//@baseUrl = http://localhost:3000/api/v1

//@baseUrl = http://192.168.16.178:3000/api/v1
@baseUrl = http://172.26.86.113:3000/api/v1

# @baseUrl = http://43.138.144.204:3000/api/v1

@authorization = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNzEwYzVmNjEwYzYyNGY1YzRiZjgzNCIsImlhdCI6MTY1MTY2NzcyOCwiZXhwIjoxNjUyMjcyNTI4fQ.V8A4Jur8xhP2BrgneX08TGeKNsS0xLMWMNxHl9fj0xg

# 登录

### 用户登录(管理员、顾客)
POST {{baseUrl}}/login
Content-Type: application/json

{ 
  "user_name": "customer1",
  "password": "123456"
}



# 管理员

### 管理员注册
POST {{baseUrl}}/register/admin
Content-Type: application/json

{
  "user_name": "admin2",
  "password": "123456"
}



# 顾客

### 顾客注册
POST {{baseUrl}}/register/customer
Content-Type: application/json

{
  "user_name": "customer1",
  "password": "123456",
  "name":"小程序顾客1",
  "phone":"18585963214",
  "address":"云南昆明"
}


### 更新顾客信息
PUT {{baseUrl}}/customers/620256eee9871555d8e48750
{{authorization}}
Content-Type: application/json

{
  "name": "更新顾客1",
  "phone": "18514964682",
  "address": "张杨路3611号金桥国际商业广场1座B1层"
}


### 获取顾客列表
GET {{baseUrl}}/customers?offset=0&limit=1
{{authorization}}


### 获取顾客信息
GET {{baseUrl}}/customers/620256eee9871555d8e48750
{{authorization}}


//  ToDo: 删除顾客时并不能删除user表里面的下的信息。只能删除顾客表里面的信息  
//已解决，只不过不知道要哪个版本，老版本不删除user 新版本删除user
### 删除顾客
DELETE {{baseUrl}}/customers/620256eee9871555d8e48750
{{authorization}}


# 商家

// ToDo: 顾客user_name和商家user_name会出现不能相同，因为不论顾客还是商家都属于user
### 商家注册
POST {{baseUrl}}/register/merchant
Content-Type: application/json

{
   "user_name": "merchant1",
   "password": "123456",
   "name":"民心商店",
   "phone":"15965832145",
   "introduction":"农资经营",
   "address":"云南省曲靖市"
}

// TODO: 更新商家如果ID错了，响应没有提示！请参考更新批发商的控制器，批发商的那个有提示。
### 更新商家
PUT  {{baseUrl}}/merchants/62693e2bd96fa75ef062fa45
{{authorization}}
Content-Type: application/json

{
  "name": "昆明制药厂",
  "phone": "18596857595",
  "introduction": " 昆明农药有限公司成立于1980-09-09，注册资本为1000万元人民币",
  "address": "昆明市富民县罗免镇高仓村",
  "delivery_cost": 1,
  "min_delivery_price": 10
}


### 获取商家列表
GET {{baseUrl}}/merchants?offset=0&limit=1
{{authorization}}


### 获取商家信息
GET {{baseUrl}}/merchants/6207b16c95fdf50bb04133f7
{{authorization}}


### 删除商家
DELETE {{baseUrl}}/merchants/6207b16c95fdf50bb04133f7
{{authorization}}


# 商品

### 新增商品
POST {{baseUrl}}/merchandises
{{authorization}}
Content-Type: application/json

{
  "name": "种子",
  "price": 20
  //"qrcode":1524224
}


### 更新商品信息
PUT {{baseUrl}}/merchandises/6271266e610c624f5c4bf870
{{authorization}}
Content-Type: application/json

{
  "name":"百草枯",
  "price":"20",
  "specs":"瓶",
  "productionDate":"2022-03-08",
  "shelfLife":"24",
  "manufacturer":"昆明制药厂"
}


### 获取商品列表
GET {{baseUrl}}/merchandises
{{authorization}}


### 获取商品信息
GET {{baseUrl}}/merchandises/626a06c0d96fa75ef062fcff
{{authorization}}


### 删除商品
DELETE {{baseUrl}}/merchandises/620fac3c7a5dc3356c7ab883
{{authorization}}



# 批发商


### 新增批发商
POST {{baseUrl}}/wholesalers
{{authorization}}
Content-Type: application/json

{
  "name": "亿家农资批发店"
}


### 更新批发商
PUT {{baseUrl}}/wholesalers/6273c176cb3a132d4879ae5a
{{authorization}}
Content-Type: application/json

{
  "phone":"15869324569",
  "address":"将军镇521号"
}


### 获取批发商列表
GET {{baseUrl}}/wholesalers
{{authorization}}


### 获取商家信息
GET {{baseUrl}}/wholesalers/6214db82fddf321fec5a239f
{{authorization}}


### 删除批发商
DELETE {{baseUrl}}/wholesalers/6214db82fddf321fec5a239f
{{authorization}}